### PR TITLE
Add TLS instructions and rework startup section

### PR DESCRIPTION
**Pull request by robertfoss**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@robertfoss: Can you check the error, and rebase?

**Comment by Neustradamus** [comment]
@Half-Shot: Why have you closed it?

**Comment by alphapapa** [comment]
I'm also curious about this.  Why was the `matrix-org:master` branch deleted?  Why is the `matrix.org` bridge not working for XMPP in both directions, and why can't I get an answer about this problem either on this repo (i.e. https://github.com/matrix-org/matrix-bifrost/issues/338), in the room `#bifrost:half-shot.uk`, or by emailing support@matrix.org?

**Comment by Neustradamus** [comment]
@alphapapa: Yes it is strange...

**Pull request closed without merging**
