### PR TITLE
Avatars handling, Room disco, Plumb and replies

### PR DESCRIPTION
**Pull request by maranda**
This is a rebase of #274 

Features implemented:
- Fetching of MUC occupant avatars for matrix side of the gateway
- Implementing handling of MUC avatars to set the Matrix room avatar
- Implement logics and facilities to fetch pictures off Matrix profiles and create and store hashes that require to be appended to presences to advertise avatar availability XMPP side of the gateway

Issues fixed:
- Attempt fixing mxID unescaping function to better handle multibyte chars
- Fix storage method getRoomsOfType() as it didn't handle correctly anything but group rooms
- Make sure xmppWriteToStream() always passes a string both when writing to the stream and buffering stanzas, as passing an element now causes promises to break
- Make room disco responses consistent, add occupant count and descriptions, also remove rooms with uppercase letters into aliases as they aren't compliant with XMPP addressing and will be normalized by servers
- Fix reversed comparison in plumbing and make logging a bit consistent in case plumbing is disabled, also fix sanitizing of properties
- Fix annoyingly long mxIDs in replies, do remove or replace the nametag trailers in case the mxID exceedes 25 characters
- Fix missing body tag envelope in XHTML-IM messages (that addresses #292)

### CODE REVIEW

**Comment by Half-Shot** [comment]
Hiya, thanks for the super impressive set of changes. It's really appreciated. As it stands though this is going to be quite difficult to merge due to the number of changes in the PR -- we like to keep PRs relatively small and self contained because it allows us to review and assess the damage easier. 

This PR is some 68 commits long, so in the future if you could keep the changes a bit smaller (and submit multiple PRs if needed) that would be appreciated!

**Comment by maranda** [comment]
I will do for the future, but for this one it was practically impossible to bisect it in multiple ones as I had to resync and also resolve conflicts multiple times (not counting rebases to cleanup). If it's too problematic to merge no problem, feel also free to change / use it at your leasure.

**Comment by Neustradamus** [comment]
@Half-Shot: Any news about improvements?

**Comment by Neustradamus** [comment]
@Half-Shot: Any news about all improvements of @maranda?

**Comment by maranda** [comment]
Highly outdated, and very hard to keep in Sync by now.

**Comment by Neustradamus** [comment]
@maranda: Badly, it is sad...

cc @Half-Shot, @matrix-org team members.

**Pull request closed without merging**
